spring.application.name=expense

server.port=${PORT:8080}

# 2. Database URL (Render provides 'DATABASE_URL' or 'SPRING_DATASOURCE_URL')
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/expense_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

# 3. Hibernate (Crucial for PostgreSQL on Render)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update



